spring:
  application:
    name: hospital-gateway
server:
  port: 4900
  http2:
    enabled: true
  servlet:
    context-path: /api
logging:
  charset:
    console: UTF-8
  level:
    org:
      springframework: info
      # Add DEBUG level for WebClient exchange functions
      com:
        javaweb:
          hospital:
            gateway: info
  file:
    name: logging/hospital-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
      total-size-cap: 2GB
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
internal:
  service:
    patient-management: http://patient:8080/api
    appointment-management: http://appointment:8081/api/v1
springdoc:
  swagger-ui:
    enabled: true